"""create nutrition, unit and translation tables

Revision ID: 01b70f4356c8
Revises: 298eca30b0cf
Create Date: 2026-02-13 14:17:21.947164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '01b70f4356c8'
down_revision: Union[str, Sequence[str], None] = '298eca30b0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruits',
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scientific_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fruits_slug'), 'fruits', ['slug'], unique=True)
    op.create_table('units',
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_slug'), 'units', ['slug'], unique=True)
    op.create_table('fruit_translations',
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fruit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fruit_id'], ['fruits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fruit_id', 'language', name='uq_fruit_language')
    )
    op.create_index(op.f('ix_fruit_translations_language'), 'fruit_translations', ['language'], unique=False)
    op.create_table('nutrients',
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrients_slug'), 'nutrients', ['slug'], unique=True)
    op.create_table('unit_translations',
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_form', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_form', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'language', name='uq_unit_language')
    )
    op.create_index(op.f('ix_unit_translations_language'), 'unit_translations', ['language'], unique=False)
    op.create_table('fruit_nutrient_link',
    sa.Column('fruit_id', sa.Integer(), nullable=False),
    sa.Column('nutrient_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fruit_id'], ['fruits.id'], ),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrients.id'], ),
    sa.PrimaryKeyConstraint('fruit_id', 'nutrient_id')
    )
    op.create_table('nutrient_translations',
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutrient_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nutrient_id', 'language', name='uq_nutrient_language')
    )
    op.create_index(op.f('ix_nutrient_translations_language'), 'nutrient_translations', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrient_translations_language'), table_name='nutrient_translations')
    op.drop_table('nutrient_translations')
    op.drop_table('fruit_nutrient_link')
    op.drop_index(op.f('ix_unit_translations_language'), table_name='unit_translations')
    op.drop_table('unit_translations')
    op.drop_index(op.f('ix_nutrients_slug'), table_name='nutrients')
    op.drop_table('nutrients')
    op.drop_index(op.f('ix_fruit_translations_language'), table_name='fruit_translations')
    op.drop_table('fruit_translations')
    op.drop_index(op.f('ix_units_slug'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_fruits_slug'), table_name='fruits')
    op.drop_table('fruits')
    # ### end Alembic commands ###
