"""add rda field to nutritions

Revision ID: 1cbdb6239436
Revises: 01b70f4356c8
Create Date: 2026-02-13 23:19:26.112840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbdb6239436'
down_revision: Union[str, Sequence[str], None] = '01b70f4356c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrients', sa.Column('rda', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrients', 'rda')
    # ### end Alembic commands ###
